matrix:
  include:
    - language: python
      python:
        - 3.6

      install: true
      script: python3 -m unittest discover -s . -p '*_test.py'

    - language: ruby
      rvm:
        - 2.4.0
      gemfile: ./GemFile  
      script: bundle exec rspec ./spec
